#!/usr/bin/env bash
#Install nginx and configure to say hello world
sudo apt update
sudo apt install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bck
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
