#!/usr/bin/env bash
#Configure an ubuntu machine to install nginx
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
