#!/usr/bin/env bash
#script to install nginx on a server

sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" >  hello
sudo cp  hello /var/www/html/index.nginx-debian.html
rm hello
sudo service nginx restart
