#!/usr/bin/env bash
# Configure my nginx server

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bck

echo "Hello World!" | sudo tee /var/www/html/index.html

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart

