#!/usr/bin/env bash
#Create a custom 404 error page

#sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	error_page 404 /error_404.html;
        location = /error_404.html {
                root /usr/share/nginx/html;
                internal;
        }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
