#!/usr/bin/env bash
#Create a custom 404 error page

#sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html;
	location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

	error_page 404 /error_404.html;
        location = /error_404.html {
                root /usr/share/nginx/html;
                internal;
        }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
