#!/usr/bin/env bash
#Transfers a file from our client to a server
path="$1"
ip="$2"
name="$3"
pathscp="$4"
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$path" "$user"@"$ip":"$pathscp"
fi
