#!/usr/bin/env bash
#PRINT THE TIME FOR 12 hours and 59 minutes

hours=0
minutes=1

while [ "$hours" -le 12 ]
do
	echo "Hour: $hours"
	while [ "$minutes" -lt 60 ]
	do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	minutes=1
	hours=$((hours+1))
done
