#!/usr/bin/env bash
#start apache on a docker container and return a page 
#containing "hello holberton"
apt-get install apache2 -y
echo "ServerName localhost" >> /etc/apache2/apache2.conf
/etc/init.d/apache2 start
