#!/usr/bin/env bash
#run nginx as user nginx
sudo chown nginx:nginx /etc/nginx
sudo chown nginx:nginx /var/log/nginx
sudo chown nginx:nginx /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
su nginx service nginx restart
~                                 
